--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/NhanAZ/libRegRsp
build-by-default: true
branches:
- master
projects:
  libRegRsp:
    path: ""
    model: virion
    type: library
...
